from F01_Login import *
def Help(role : str) -> str:
    if role == "":
        print("\n=========== HELP ===========\n")
        print("1. login")
        print("untuk masuk menggunakan akun")
        print("2. exit")
        print("untuk keluar dari program dan kembali ke terminal")
    elif Login_status() == True:
        if role == "bandung_bondowoso":
            print("\n=========== HELP ===========\n")
            print("1. logout")
            print("untuk keluar dari akun yang digunakan sekarang")
            print("2. summonjin")
            print("untuk memanggil jin dari dunia lain")
            print("3. hapusjin")
            print("untuk mengembalikan jin ke dunia lain")
            print("4. ubahjin")
            print("untuk mengubah tipe jin")
            print("5. batchkumpul")
            print("untuk mengerahkan seluruh jin untuk mengumpulkan bahan")
            print("6. batchbangun")
            print("untuk mengerahkan seluruh jin untuk membangun candi")
            print("7. laporanjin")
            print("untuk mengetahui kinerja jin")
            print("8. laporancandi")
            print("untuk mengetahui progress pembangunan candi")
        elif role == "roro_jonggrang":
            print("\n=========== HELP ===========\n")
            print("1. logout")
            print("untuk keluar dari akun yang digunakan sekarang")
            print("2. hancurkancandi")
            print("untuk menghancurkan candi yang telah dibangun oleh jin")
            print("3. ayamberkokok")
            print("menyelesaikan permainan")
        elif role == "jin_pembangun":
            print("=========== HELP ===========")
            print("1. logout")
            print("untuk keluar dari akun yang digunakan sekarang")
            print("2. jinpembangun")
            print("membangun candi")
        elif role == "jin_pembangun":
            print("\n=========== HELP ===========\n")
            print("1. logout")
            print("untuk keluar dari akun yang digunakan sekarang")
            print("2. bangun")
            print("untuk membangun candi")
        elif role == "jin_pengumpul":
            print("\n=========== HELP ===========\n")
            print("1. logout")
            print("untuk keluar dari akun yang digunakan sekarang")
            print("2. kumpul")
            print("untuk mengumpulkan bahan")